### PR TITLE
Notes - Idel Ishbaev

### PR DESCRIPTION
**Pull request by IdelIshbaev**

### CODE REVIEW

**Comment by SergeiSa** [comment]
What are the .DS_Store files?

**Comment by IdelIshbaev** [comment]
Files created when we clone repo to MacBook


> What are the .DS_Store files?

**Comment by SergeiSa** [comment]
So why do we need to commit them?..

**Comment by IdelIshbaev** [comment]
> So why do we need to commit them?..

When I did not push them - same problem(checker)

**Comment by SergeiSa** [comment]
I can merge the request even with the check errors, I think they might be external to your commit. But please clean up the commit before...

**Comment by IdelIshbaev** [comment]
> I can merge the request even with the check errors, I think they might be external to your commit. But please clean up the commit before...

ok, 2 minutes

**Comment by IdelIshbaev** [comment]
> I can merge the request even with the check errors, I think they might be external to your commit. But please clean up the commit before...

Check now please

**Comment by SergeiSa** [comment]
I still see those same files.

**Pull request closed without merging**
