### PR TITLE
fix: optimal J is the minimum of all cost functions

### PR DESCRIPTION
**Pull request by Birdi7**
The optimal J(i.e. J star) is the minimum of all possible cost functions. I see no meaning in `inf` symbol there

### CODE REVIEW

**Comment by aabounegm** [comment]
`inf` means infimum, which is similar to the minimum, but slightly different in some cases.
https://math.stackexchange.com/questions/342749/what-is-the-difference-between-minimum-and-infimum

**Comment by Birdi7** [comment]
Is it applicable to cost function? Do there exist some cases, in which the J-star couldn't be attained?

**Comment by SergeiSa** [comment]
Very good point. I don't see any counter-examples, and there are sources that use min in the definition. But, even if there are no counterexamples, infimum formulation is still correct; I will wait with this pull request until I have a good look in the literature.

**Comment by SergeiSa** [comment]
Guess we let it be for now. I will keep the problem in mind though

**Pull request closed without merging**
