### PR TITLE
added notes for parameter estimation lecture

### PR DESCRIPTION
**Pull request by MatrosovaTalia**

### CODE REVIEW

**Comment by SergeiSa** [comment]
Can you either add PDF to the commit or add the doc to the automatically generated PDF functionality  in the https://github.com/SergeiSa/Linear-Control-Slides-Spring-2020/blob/master/.github/workflows/blank.yml ?

**Comment by MatrosovaTalia** [comment]
> Can you either add PDF to the commit or add the doc to the automatically generated PDF functionality in the https://github.com/SergeiSa/Linear-Control-Slides-Spring-2020/blob/master/.github/workflows/blank.yml ?

Added pdf file

**Comment by SergeiSa** [comment]
"The problem is that to find the control law we need to know the higher order derivatives. " - that is not true =)

" we do not know actual values of $\bm{ \ddot{q},\dot{q},q}$ " - we actually assume that we do.

Please fix those, and I'll accept the notes. I will ask others to contribute to them though or to make a different version, there are details that not covered and and the narration can improve. Tank you for starting the process, it is very nice of you, hope it would help other students!

**Comment by MatrosovaTalia** [comment]
I fixed the mistakes you mentioned

**Pull request merged**
